file_manager/urls.py
from django.conf.urls import url
from file_manager import views


urlpatterns = [
    url('file/upload/', views.FileUpload.as_view(), name='file_upload'),
    url('file/download/(?P<file_id>.*?)$', views.FileDownload.as_view(), name='file_download'),
    url('file/rename/$', views.FileRename.as_view(), name='file_rename'),
    url('file/delete/$', views.FileDelete.as_view(), name='file_delete'),

    url('dirs/view/(?P<dir_id>.*?)$', views.DIRView.as_view(), name='dir_view'),
    url('dirs/create/$', views.DIRCreate.as_view(), name='dir_create'),
    url('dirs/list/', views.DIRList.as_view(), name='dir_list'),
    url('dirs/delete/$', views.DIRDelete.as_view(), name='dir_delete'),

    # url('api/', include('file_manager.api.urls')),

    url('$', views.FilesView.as_view(), name='home'),

]

s3_file_manager/urls.py
from django.urls import include, path
from django.contrib import admin
from file_manager import urls as fm_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(fm_urls))
]

file_manager/forms.py
from django import forms


class FileUploadForm(forms.Form):
    directory = forms.Select()
    filename = forms.CharField(max_length=50, required=False)
    file = forms.FileField()

templates/base.html
{% load rest_framework %}
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">

    <title>File Manager</title>
  </head>

  <body>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Disabled</a>
              <a class="dropdown-item" href="#">Disabled</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Disabled</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="card-body text-center mb-3">
        <div class="container">
        <ul class="nav nav-pills nav-fill">
          <li class="nav-item">
            <a type="button" class="nav-link active" data-toggle="modal" data-target="#CreateDirModal" data-whatever="@getbootstrap">Create DIR</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'file_upload' %}">Upload File</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="col"></div>
    {% endblock %}

    {% include 'modals/modal_create_dir.html' with filename=filename %}

      <div class="card-body mb-3">
        {% block content %}{% endblock %}
      </div>

    {% block ctrl %}{% endblock %}

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/home.js' %}"></script>
    {% block js %}
    {% endblock %}

  </body>
</html>

templates/dirs_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% csrf_token %}
<div class="container form-group">
    <button type="button" class="btn btn-outline-primary" onclick="history.back();">Back</button>
</div>

<div class="container">

  <table class="table table-bordered table-striped text-center">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Type</th>
        <th scope="col">Size</th>
        <th scope="col">Modified</th>
        <th scope="col">Download</th>
        <th scope="col">Rename</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>

    {% include 'modals/modal_rename_file.html' with filenames=filenames %}

    {% for nested_dir in nested_dirs %}
            <tr id="dir_{{ nested_dir.id }}">
                <th scope="row">#</th>
                <td><a href="{% url 'dir_view' dir_id=nested_dir.id %}" class="">{{ nested_dir.name }}</a></td>
                <td>DIR</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><a type="button" onclick="delete_dir({{ nested_dir.id }})" class="">Delete DIR</a></td>
            </tr>
    {% endfor %}

    {% for filename in filenames %}

        <tr id="tr{{ filename.id }}">
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ filename.aws_key }}</td>
            <td>{{ filename.type }}</td>
            <td>{{ filename.size }}</td>
            <td>{{ filename.last_modified }}</td>
            <td><a href="{% url 'file_download' file_id=filename.id %}" class="">Download</a></td>
            <td>
                <a type="button" data-toggle="modal" data-target="#RenameModal_{{ filename.id }}">Rename</a>
            </td>
            <td><a type="button" onclick="delete_file({{ filename.id }})" class="">Delete</a></td>
        </tr>

    {% endfor %}
    </tbody>
  </table>

</div>

{% endblock %}

{% block js %}
<script type="text/javascript" language="javascript" src="{% static 'js/csrfSetUp.js' %}"></script>
<script type="text/javascript" src="{% static 'js/modal/create_dir.js' %}"></script>
<script type="text/javascript" src="{% static 'js/modal/rename_file.js' %}"></script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% csrf_token %}

<div class="container">

    <div class="card-columns">

        {% for filename in filenames %}
            <div class="card">
                <div class="card-body">
                    <a href="{% url 'dir_view' dir_id=filename.id %}">
                        <img src="{% static 'img/aws_s3_logo.png' %}" class="card-img-top">
                    </a>
                  <h5 class="card-title">
                      <a href="{% url 'dir_view' dir_id=filename.id %}" class="">{{ filename.name }}</a>
                  </h5>
                  <p class="card-text">Total objects: {{ filename.files.count }}</p>
                  <p class="card-text"><small class="text-muted">
                      {% if filename.last_updated_min %}
                        Last updated {{ filename.last_updated_min }} mins ago
                      {% endif %}

                  </small></p>
                </div>
            </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

{% block js %}
<script type="text/javascript" language="javascript" src="{% static 'js/csrfSetUp.js' %}"></script>
<script type="text/javascript" src="{% static 'js/modal/create_dir.js' %}"></script>
<script type="text/javascript" src="{% static 'js/modal/rename_file.js' %}"></script>

{% endblock %}

templates/modals.html
<!-- Rename File Modal -->
<div class="modal fade" id="RenameModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Rename</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="input-group mb-5">

          <div class="input-group-prepend">
              <span class="input-group-text" id="folder">New Name</span>
            </div>
            <input type="text" class="form-control" id="new_file_name"
                   aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
            <div class="input-group-append">
              <span class="input-group-text" id="new_file_name_ext">.pdf</span>
            </div>
            <div class="container form-group">
              <div class="alert alert-danger" id="alert_file_errors" role="alert"></div>
            </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" onclick="rename_file({{ filename.id }})" class="btn btn-primary">Save</button>
      </div>
    </div>
  </div>
</div>

templates/upload.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container form-group">
    <button type="button" class="btn btn-outline-primary" onclick="history.back();">Back</button>
</div>

<div class="container">

    <div class="col">
        {% if alert %}
            <div class="alert alert-warning alert-dismissible fade show alert-dark" role="alert">
              <strong>{{ alert.msg }}</strong> {{ alert.filename }}.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endif %}
    </div>

    <form class="was-validated" method="POST" action="/file/upload/" enctype=multipart/form-data> {% csrf_token %}

        <div class="form-row">
            <div class="input-group input-group-lg mb-3">

                <div class="container"><label for="id_directory">Select Folder</label></div>
                <select class="custom-select custom-select-lg mb-3" name="directory" id="id_directory">
                </select>

            </div>
        </div>

        <div class="form-row mb-3">
            <div class="custom-file">
                <input type="file" class="custom-file-input" name="file" id="id_file">
                <label class="custom-file-label" for="id_file">Choose file</label>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Upload</button>

    </form>
</div>

{% endblock %}

{% block js %}
    <script type="text/javascript" language="javascript" src="{% static 'js/csrfSetUp.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/file_upload.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/modal/create_dir.js' %}"></script>
{% endblock %}